### ISSUE TITLE
Detect alias update even if user does not press Enter

### ISSUE THREAD

**Issue by pm64** [muhammadv-i/obsidian-frontmatter-alias-display#10]
Currently, a change to a note's alias is only detected if the user hits the enter key at the end of the alias frontmatter line.

If possible to implement simply without affecting performance, changes should be detected regardless of whether the user hits enter or not. I'm not familiar with Obsidian's API, but perhaps the check could be done whenever Obsidian auto-saves the current note?

It's just a display issue, and any unsynchronized changes are resolved the next time Obsidian starts, but would be nice to have this added responsiveness.

**Comment by matthewkeating** [comment]
@pm64 I implemented this feature [here](https://github.com/matthewkeating/display-alias-with-file-title).

**Comment by notmuhammad** [comment]
Great work! Thank you for continuing on and making an improved version of my plugin.
