### ISSUE TITLE
Alias vs aliases

### ISSUE THREAD

**Issue by mutachre** [muhammadv-i/obsidian-frontmatter-alias-display#2]
I noticed that the plugin only works if the entry is listed as _aliases_ but not as _alias_.

**Comment by muhammadv-i** [comment]
Thanks for letting me know, Mutachre! I have gone ahead and fixed the issue, please try again and let me know if it still persists.

**Comment by ReaderGuy42** [comment]
Could you also add support for capital letters, e.g. `Alias: ` 
Thanks :)
