### ISSUE TITLE
"aliases" are not displaying in file view.

### ISSUE THREAD

**Issue by mattthemarketer** [muhammadv-i/obsidian-frontmatter-alias-display#7]
Initially, this was working great. I've been toying with using "unique" file names, trying to leverage a sorta zettelkasten method. Now none of the aliases are showing in the file view.

**Comment by notmuhammad** [comment]
Obsidian recently updated to version 1.2.8 so consequently I had to update the plugin to make it work with this version. Did you update both Obsidian and my plugin?
